---
title: "Projects"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---
```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Set R chunk default options:
# -do not output all R messages in html report
# -do not output all R warnings in html report
# -set default figure widths and heights for all code blocks, unless you 
#  override them
knitr::opts_chunk$set(
  message = FALSE, warning = FALSE, fig.width = 16/2, fig.height = 9/2
)
```
```{r, echo = FALSE}
#loading libraries

library(ggplot2)
library(lubridate)
library(tidyr)
library(readr)
library(mapview)
library(tidyverse)
library(sf)
library(htmltools)
library(geojsonio)
library(leaflet)
library(USAboundaries)
library(maps)
library(editData)
library(sp)
library(tmaptools)
library(raster)
library(dplyr)
library(mapview)
library(readr)
```

<p>&nbsp;</p>

# Under Construction

You can find some of my projects on my [GitHub](https://github.com/epartakki/)

&nbsp;
<hr />
<p style="text-align: center;">Portfolio by <a href="https://github.com/epartakki/">Eleni Partakki</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>elenipartakki at gmail dot com</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://twitter.com/epartakki" class="fa fa-twitter"></a>
    <a href="https://www.linkedin.com/in/elenipartakki/" class="fa fa-linkedin"></a>
    <a href="https://github.com/epartakki" class="fa fa-github"></a>
</p>

&nbsp;


